# pre-commit configuration file
#
# TL;DR
#   pre-commit runs a series of formatters and linters on every commit.
#   If throws an error, it's usually already fixed the problem and just
#   wants you to have a look at the changes it made.
#   This file sets up pre-commit to do some basic checks, fix whitespace
#   and line endings, and run stylish-haskell.
#   To setup the pre-commit hooks, you'll need pre-commit, and install the
#   hooks by running `pre-commit install` from the repository root.
#
# See: https://pre-commit.com

# Exclude golden standard generated JSON files:
exclude: '^.*\.golden$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/ikamensh/flynt/
    rev: "0.78"
    hooks:
      - id: flynt
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1"
    hooks:
      - id: mypy
        name: mypy (vehicle-python)
        args:
          - "--config-file=vehicle-python/pyproject.toml"
        additional_dependencies:
          - "types_setuptools >=45"
          - "types_pygments >=2.14"
          - "packaging >=23"
        files: '^vehicle-python\/.*\.py$'
  - repo: local
    hooks:
      - id: cabal-fmt
        name: "format cabal with cabal-fmt"
        entry: ./scripts/cabal-fmt
        language: script
        types: [file, text]
        files: ^.*\.cabal$
        args: [--check, --inplace]
      - id: ormolu
        name: "format haskell with ormolu"
        entry: ./scripts/ormolu
        language: script
        types: [haskell]
        args: [--mode inplace, --check-idempotence]

# Do not run local hooks on pre-commit CI:
ci:
  skip: [cabal-fmt, ormolu]
